### ISSUE TITLE
use the "image" option in compose rather than a full service and dockerfile

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io-playground/express-mongo-sample#4]
A suggestion would be to use the `image:` field in the compose for the mongo service, since it doesn't seem to need any thing specific in the service. An example snippet for this is:
```
services:
  mongo:
    image: arm64v8/mongo
    restart: always
    volumes:
      - 'mongo-data:/data/db'
    expose:
      - "27017"
```
